/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administration;
import com.sun.jdi.connect.spi.Connection;
import sql_methods.*;
import javax.swing.JOptionPane;

/**
 *
 * @author rdaniels
 */
public class frm_login extends javax.swing.JFrame {

    /**
     * Creates new form frm_login
     */
    
    sqlMethods metodo = new sqlMethods();
    
    public frm_login() {
        initComponents();
        setLocationRelativeTo(null); // colocar la ventana en el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre_usuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnGo_register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(184, 223, 216));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("LOGIN");

        txtNombre_usuario.setToolTipText("Nombre de usuario");
        txtNombre_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_usuarioActionPerformed(evt);
            }
        });

        txtContraseña.setToolTipText("Contraseña");

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administration/icons/key.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnGo_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administration/icons/register.png"))); // NOI18N
        btnGo_register.setText("Registrarse");
        btnGo_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGo_registerActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de usuario");

        jLabel3.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGo_register, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(txtContraseña))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtNombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo_register, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_usuarioActionPerformed

    private void btnGo_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGo_registerActionPerformed
        // TODO add your handling code here:
        frm_register ventana = new frm_register(); // instanciamos la clase register
        ventana.setVisible(true); // la hacemos visible 
        this.dispose(); 
    }//GEN-LAST:event_btnGo_registerActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        String buscar_usuario = metodo.buscarUsuarioRegistrado(txtNombre_usuario.getText(), txtContraseña.getText());
        
        // este if anidado es una validacion pra saber si alguno de los text box esta bacio no entrar al sistema
        if(txtNombre_usuario.getText().trim().isEmpty() != true){
        
        
            if(txtContraseña.getText().trim().isEmpty() != true){
                
                if(txtNombre_usuario.getText().equals("root") && txtContraseña.getText().equals("drareneon")){
            
                JOptionPane.showMessageDialog(this, "Se ha iniciado seccion como administrador (◍•ᴗ•◍)❤");
            
                frm_system ventana = new frm_system();
            
                ventana.lbluser.setText("Shinji");
            
                ventana.setVisible(true);
            
                this.dispose();
        
                }
                
                else if (buscar_usuario.equals("El usuario a sido encontrado")){
            
                    String buscar_nombre = metodo.buscarUsuario(txtContraseña.getText());
        
                    JOptionPane.showMessageDialog(this, "Buenvenido (a) (◍•ᴗ•◍)❤ \n " + buscar_nombre);
            
                    frm_system ventana = new frm_system();
            
                    ventana.lbluser.setText(buscar_nombre);
            
                    ventana.setVisible(true);
            
                    this.dispose();
            
                }
                else if (buscar_usuario.equals("Uno de los datos introducidos a sido encontrado pero otro no")){
                
                    JOptionPane.showMessageDialog(this, "Uno de los campos introducidos a sido encontrado pero otro no ( ͡° ͜ʖ ͡°) ");
                }
                else{
        
                    JOptionPane.showMessageDialog(this, "Datos erroneos el usuario y/o la contraseña no estan registrados ٩(ↀДↀ)۶");
            
                } 
            }
            else{
                JOptionPane.showMessageDialog(this, "Falta llenar el campo de contraseña ٩(ↀДↀ)۶");
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Falta llenar el campo de nombre de usuario ٩(ↀДↀ)۶");
        }
             
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnGo_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre_usuario;
    // End of variables declaration//GEN-END:variables
}
