/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administration;
import administradorBL.administradorBL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sql_methods.*;
/**
 *
 * @author rdaniels
 */
public class frm_system extends javax.swing.JFrame {

    /**
     * Creates new form frm_system
     */
    
    DefaultTableModel modelo; // esto es para poder trabajar con mysql y la tabla
    
    public frm_system() {
        initComponents();
        setLocationRelativeTo(null);
        
        String[] columnas = {"nombre", "apellido", "telefono", "correo", "usuario"}; // creamos las columnas
        
        modelo = new DefaultTableModel(null, columnas); // agregamos columnas
        tblUsers.setModel(modelo); // carga columnas con la info
        
        this.desplegarDatos(); // despliega los datos en la tabla 
        
        this.limpiar_datos(); // limpia los datos del txt
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(184, 223, 216));

        jLabel1.setText("Hola: ");

        lbluser.setText(".");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Telefono", "Correo", "Usuario"
            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido: ");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Usuario:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administration/icons/plus.png"))); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administration/icons/delete (1).png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administration/icons/refresh.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administration/icons/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administration/icons/log-out.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellido)
                    .addComponent(txtNombre))
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbluser, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbluser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar)
                    .addComponent(btnAñadir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
        sqlMethods metodo = new sqlMethods();
        
        administradorBL adminTrought = consultarDatos();
        
        String sql_insercion = String.format("INSERT INTO adminSystem VALUES "
                + "                         ('%s', '%s', '%s', '%s', '%s')", 
                                            adminTrought.getNombre(), adminTrought.getApellido(), adminTrought.getTelefono(), adminTrought.getCorreo(), adminTrought.getUsuario());
        
        // este if anidado es una validacion pra saber si alguno de los text box esta bacio no se registrara
        if(txtNombre.getText().trim().isEmpty() != true){
            
            if(txtApellido.getText().trim().isEmpty() != true){
            
                if(txtTelefono.getText().trim().isEmpty() != true){
                    
                    if(txtCorreo.getText().trim().isEmpty() != true){
                        
                        if(txtUsuario.getText().trim().isEmpty() != true){
                       
                            metodo.ejecutarSentenciaSQL(sql_insercion);
                            JOptionPane.showMessageDialog(this, "El usuario se a agregado correctamente (◍•ᴗ•◍)❤");
                            
                            try {
                                ResultSet resultado = metodo.consultarDatos("SELECT * FROM adminSystem");
                                
                                while(resultado.next()){
                                    System.out.println(resultado.getString("nombre"));
                                    System.out.println(resultado.getString("apellido"));
                                    System.out.println(resultado.getString("telefono"));
                                    System.out.println(resultado.getString("correo"));
                                    System.out.println(resultado.getString("nombre_usuario"));
                                    this.desplegarDatos();
                                    this.limpiar_datos();
                                }
                            } catch (Exception e) {
                                System.out.println("Opps algo ocurrio procesando los datos " + e);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "falta llenar el campo de usuario ٩(ↀДↀ)۶");
                        }

                    }
                    else{
                        JOptionPane.showMessageDialog(this, "falta llenar el campo de correo ٩(ↀДↀ)۶");
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Falta llenar el campo de contraseña ٩(ↀДↀ)۶");
                }
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Falta llenar el campo de apellido ٩(ↀДↀ)۶");
            }
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Falta llenar el campo de nombre ٩(ↀДↀ)۶");
        }
    }//GEN-LAST:event_btnAñadirActionPerformed
    
    // mostrar los datos de la dba en la tabla
    public void desplegarDatos(){
        sqlMethods metodo = new sqlMethods();
        
        while(modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
    
        try {
               ResultSet resultado = metodo.consultarDatos("SELECT * FROM adminSystem");
                                
               while(resultado.next()){

                    String[] usuario = {resultado.getString("nombre"), resultado.getString("apellido"), resultado.getString("telefono"), resultado.getString("correo"), resultado.getString("nombre_usuario")};
                    modelo.addRow(usuario);
               }
        } catch (Exception e) {
            System.out.println("Opps algo ocurrio procesando los datos " + e);
        }
    }
    
    public administradorBL consultarDatos(){
        
        administradorBL adminSend = new administradorBL();
        
        adminSend.setNombre(txtNombre.getText());
        adminSend.setApellido(txtApellido.getText());
        adminSend.setTelefono(txtTelefono.getText());
        adminSend.setCorreo(txtCorreo.getText());
        adminSend.setUsuario(txtUsuario.getText());
        
        return adminSend;
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiar_datos();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    // este metodo nos permitira editar al darle click a la fina deseada 
    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){ // al darle solo un click 
            JTable resividor = (JTable) evt.getSource(); // buscaremos la columna
            
            // le pasaremos el dato de la columna los txt
            txtNombre.setText(resividor.getModel().getValueAt(resividor.getSelectedRow(), 0).toString());
            txtApellido.setText(resividor.getModel().getValueAt(resividor.getSelectedRow(), 1).toString());
            txtTelefono.setText(resividor.getModel().getValueAt(resividor.getSelectedRow(), 2).toString());
            txtCorreo.setText(resividor.getModel().getValueAt(resividor.getSelectedRow(), 3).toString());
            txtUsuario.setText(resividor.getModel().getValueAt(resividor.getSelectedRow(), 4).toString());
        }
        
        btnAñadir.setEnabled(false);
        btnEliminar.setEnabled(true);
        btnEditar.setEnabled(true);
    }//GEN-LAST:event_tblUsersMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        sqlMethods metodo = new sqlMethods();
        
        administradorBL adminTrought = consultarDatos();
        
        String sql_insercion = String.format("DELETE FROM adminSystem WHERE telefono = '" +  adminTrought.getTelefono() + "'");
        
        metodo.ejecutarSentenciaSQL(sql_insercion);
        
        this.desplegarDatos(); // refresca la tabla
        
        this.limpiar_datos(); // limpia los datos del txt
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        sqlMethods metodo = new sqlMethods();
        
        administradorBL adminTrought = consultarDatos(); // conectandonos a la dba
        
        String sql_insercion = String.format("UPDATE adminSystem SET "
                + "                         nombre = '%s', apellido =  '%s', telefono =  '%s', correo = '%s', nombre_usuario = '%s'", 
                                            adminTrought.getNombre(), adminTrought.getApellido(), adminTrought.getTelefono(), adminTrought.getCorreo(), adminTrought.getUsuario());
        
        
        metodo.ejecutarSentenciaSQL(sql_insercion);
        
        this.desplegarDatos(); // este metodo refresca la tabla
        
        this.limpiar_datos(); // limpia los datos del txt
       
    }//GEN-LAST:event_btnEditarActionPerformed
    
    // este metodo limpiara los txt y bloqueara algunos botonos que son innesesdarios por el momento
    public void limpiar_datos(){
    
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
        
        btnAñadir.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnEditar.setEnabled(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_system().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbluser;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
